class Combined:
    STAT_CATEGORIES_INTEGER = [
        "ast",
        "blk",
        "blkr",
        "dreb",
        "fg2a",
        "fg2m",
        "fg3a",
        "fg3m",
        "fga",
        "fgm",
        "fta",
        "ftm",
        "minus",
        "oreb",
        "pf",
        "pfd",
        "pfoff",
        "pftech",
        "plus",
        "plus_minus",
        "pts",
        "pts_2nd_chance",
        "pts_fastbreak",
        "pts_paint",
        "reb",
        "stl",
        "tov",
    ]
    COLUMNS_TO_RENAME = {
        "team_nba": "team",
        "4h_easy": "4hchange_easy",
        "4h_hard": "4hchange_hard",
    }
