class CombinedParameters:
    COLUMNS_TO_RENAME = {
        "team_nba": "team",
    }
    STAT_CATEGORIES_INTEGER = [
        "ast",
        "blk",
        "blkr",
        "dreb",
        "fg2a",
        "fg2m",
        "fg3a",
        "fg3m",
        "fga",
        "fgm",
        "fta",
        "ftm",
        "minus",
        "oreb",
        "pf",
        "pfd",
        "pfoff",
        "pftech",
        "plus",
        "plus_minus",
        "pts",
        "pts_2nd_chance",
        "pts_fastbreak",
        "pts_paint",
        "reb",
        "stl",
        "tov",
    ]
    NA_COLUMNS_TO_FILL = ["on_court", "easy_moment", "count_easy", "4hchange_easy", "low_ask_easy", "hard_moment",
                          "count_hard","4hchange_hard", "low_ask_hard"]
